### ISSUE TITLE
Sha value + gitsync

### ISSUE THREAD

**Issue by herrhartmann** [tomschwarz/grav-plugin-password-protection#1]
Hi, first of all thanks for this plugin! Do you see any chance to hide the generated sha-value in the frontmatter, when using gitsync?
Cheers
Simon

**Comment by qw3rtty** [comment]
@herrhartmann 
Thanks for opening this issue.
I don't know how `gitsync` is working in detail. 
But I will investigate it and let you know if there is a chance to hide it.

**Comment by qw3rtty** [comment]
@herrhartmann 
Right now there is unfortunately no way to hide a "custom" attribute on `gitsync`.
So I am not able to hide the sha-hash.

Maybe the maintainers of `gitsync` can add some functionality for this use case.
